### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ibecir** [azunic3/Projekat-OOAD#35]
1. Fali ERD
2. U dijagramu sekvenci fali metoda u kojoj dodajemo podatke (imamo validniPodaci = FALSE ali nigdje prije ne unosimo te podatke). Unos koda takodjer ima odredjenih nelogicnosti (sta nam vraca dajKod i sto ce nam to u ovom slucaju). Na dosta mjesta fale podatci koji se salju u nekoj od metoda
3. Za strukturalne patterne dodati i klasni dijagram za one patterne koje cete implementirati u sistemu kako bismo imali jasnu sliku i na vrijeme vidjeli da li ce se pattern dobro implementirati.

**Comment by ibecir** [comment]
1. zavrseno
2 i 3 ostalo

**Comment by azunic3** [comment]
@ibecir mozete li pogledati detaljnije patterne?
