### ISSUE TITLE
Patterni

### ISSUE THREAD

**Issue by ibecir** [azunic3/Projekat-OOAD#39]
**Strukturalni pattern
------------------------**
Mozete izbaciti bridge design pattern. Hajde samo malo bolje pogledajte svoj decorator pattern, cijeli cilj decorator patterna jeste da mjenjate ponasanje neke Base klase sa nekim izvedenim klasama. Pogledajte sljedeci tutorijal (https://refactoring.guru/design-patterns/decorator). Vi to sa trenutnom postavkom i ne radite bas, mozda Vam fali neka metoda ali ne iskoristavate ono sto je cilj decorator patterna.
Bridge design pattern ima isti problem, njegov cilj jeste da se velike klase ili nekoliko klasa razdvoje u 2 hijerarhije koje ce se poslije nezavisno razvijati. To kod Vas ne vidim, naravno mozda nesto fali u dijagramu, ili ja ne shvatam najbolje razlog ovakve implementacije, ako je tako mozete mi bolje pojasniti. Molim Vas da pogledate sljedeci primjer kako izgleda Bridge pattern https://refactoring.guru/design-patterns/bridge.

**Paterni ponasanja
----------------------**
Strategy pattern je dobar kao i State pattern

**Kreacijski patterni
-----------------------**
Factory Method pattern je dobar kao i Prototype pattern.

**Comment by azunic3** [comment]
Hvala puno, promijenit ću. @ibecir
