### ISSUE TITLE
Activitiy diagrams 5/11

### ISSUE THREAD

**Issue by azunic3** [azunic3/Projekat-OOAD#7]
@xxaidazameticaxx

**Comment by xxaidazameticaxx** [comment]
![Dijagram aktivnosti (login) vpd](https://user-images.githubusercontent.com/115507855/229375161-d3f7f7da-f1bd-461d-8bf8-1d826cb9cc60.png)
![Dijagram aktivnosti (registracija) vpd](https://user-images.githubusercontent.com/115507855/229375164-e69aeefc-599e-45c2-b6da-504aaed5447f.png)
![Dijagram aktivnosti (narudžba) vpd](https://user-images.githubusercontent.com/115507855/229375167-7a41ea90-4bf6-4a7f-a3d1-ddb0b8f2a37b.png)
![Dijagram aktivnosti (Best sellers) vpd](https://user-images.githubusercontent.com/115507855/229375168-55628e67-6016-4bb0-b997-9fabee619137.png)
![Dijagram aktivnosti(pregled i pretraživanje) vpd](https://user-images.githubusercontent.com/115507855/229375169-ac451735-fb47-42fb-91d4-66e3bebf7cce.png)
